name: BSN Frontend Pipeline
on:
  push:
    branches:
      - CI/CD_pipeline
    paths:
      - book_social-ui/**
      - docker/frontend/**
      - .github/workflows/*-frontend.yml
      - 'docker-compose.yml'

jobs:
  build-image:
    name: Build FE Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract project version
        id: extract_version
        run: |
          cd book-social-ui
          echo "VERSION=$(jq -r '.version' package.json)">>$GITHUB_OUTPUT
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build and push to docker
        uses: docker/build-push-action@v5
        with:
          context: book-social-ui
          file: docker/frontend/Dockerfile
          push: true
          platforms: 'x86|x64'
          tags: ${{secrets.DOCKER_USERNAME}}/bsn-ui:${{steps.extract_version.outputs.VERSION}}, ${{secrets.DOCKER_USERNAME}}/bsn-ui:latest

  deploy:
    name: Deploy frontend
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Create deployment folder
        run: ssh ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}} "mkdir -p ci-cd"
      - name: Docker compose file
        run: scp docker-compose.yml ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}}:ci-cd/docker-compose.yml
      - name: Set ENV variables
        run: |
          ssh ${{secrets.VPS_USERNAME}}@${{secrets.VPS_IP}}<<EOF
          cd ci-cd
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF